runtime: python311

env: flex

entrypoint: gunicorn -b :$PORT quotapath.wsgi:application

runtime_config:
  python_version: 3.11

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10

env_variables:
  DEBUG: "False"
  SECRET_KEY: "your-secret-key-here"
  DATABASE_URL: "postgresql://username:password@host:port/database"
  REDIS_URL: "redis://host:port"
  DJANGO_SETTINGS_MODULE: "quotapath.settings_production"

vpc_access_connector:
  name: "projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME"

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always